# Generated by Django 2.2.4 on 2019-09-29 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_image', models.ImageField(upload_to='', verbose_name='房屋图片', width_field=1024)),
                ('width', models.IntegerField(max_length=10, verbose_name='大小')),
                ('height', models.IntegerField(max_length=10, verbose_name='高')),
                ('direction', models.CharField(max_length=256, verbose_name='描述')),
                ('status', models.CharField(choices=[('闲置', '0'), ('已售', '1'), ('其他', '2')], max_length=1, verbose_name='房屋状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog2.UserProfile', verbose_name='所属用户')),
            ],
        ),
    ]
