# Generated by Django 2.2.4 on 2019-09-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0003_auto_20190929_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_info',
            name='house_no',
            field=models.CharField(default=None, max_length=5, verbose_name='房号'),
        ),
        migrations.AlterField(
            model_name='house_info',
            name='height',
            field=models.CharField(max_length=10, verbose_name='高'),
        ),
        migrations.AlterField(
            model_name='house_info',
            name='width',
            field=models.CharField(max_length=10, verbose_name='大小'),
        ),
    ]
