# Generated by Django 2.2.4 on 2019-09-29 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0004_auto_20190929_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_info',
            name='status',
            field=models.CharField(choices=[('0', '闲置'), ('1', '已售'), ('2', '其他')], default='闲置', max_length=1, verbose_name='房屋状态'),
        ),
        migrations.AlterField(
            model_name='house_info',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog2.UserProfile', verbose_name='所属用户'),
        ),
    ]
