# Generated by Django 2.2.4 on 2019-09-29 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0005_auto_20190929_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_info',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog2.UserProfile', verbose_name='所属用户'),
        ),
    ]
