# Generated by Django 2.2.4 on 2019-09-29 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0007_auto_20190929_1612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='House_Info',
            new_name='HouseInfo',
        ),
    ]
