# Generated by Django 2.2.4 on 2019-09-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0008_auto_20190929_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='status',
            field=models.CharField(choices=[(0, '闲置'), (1, '已售'), (2, '其他')], max_length=1, verbose_name='房屋状态'),
        ),
    ]
