# Generated by Django 2.2.4 on 2019-09-30 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0010_auto_20190929_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='monthly_pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_rate', models.CharField(max_length=30, verbose_name='水费')),
                ('power_rate', models.CharField(max_length=30, verbose_name='电费')),
                ('house_rent', models.CharField(max_length=30, verbose_name='房费')),
                ('else_rate', models.CharField(blank=True, max_length=30, null=True, verbose_name='其他费用')),
                ('remark', models.CharField(blank=True, max_length=30, null=True, verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog2.UserProfile', verbose_name='用户')),
            ],
        ),
    ]
