# Generated by Django 2.2.4 on 2019-09-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0012_monthly_pay_house_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_pay',
            name='payment_status',
            field=models.CharField(choices=[('0', '未支付/欠费'), ('1', '已支付'), ('2', '异常')], default='0', max_length=3, verbose_name='支付状态'),
        ),
    ]
