# Generated by Django 2.0.1 on 2019-10-06 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0013_monthly_pay_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='house_no',
            field=models.CharField(default=None, max_length=5, unique=True, verbose_name='房号'),
        ),
        migrations.AlterField(
            model_name='monthly_pay',
            name='house_no',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog2.HouseInfo', to_field='house_no'),
        ),
    ]
