# Generated by Django 2.1.4 on 2019-11-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0019_auto_20191021_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_out_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Housing_Supporting_Facilities_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='house_image',
            field=models.ImageField(upload_to='img/', verbose_name='房屋图片'),
        ),
    ]
