# Generated by Django 2.1.4 on 2019-11-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0020_auto_20191127_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseinfo',
            name='aircon',
            field=models.CharField(max_length=4, null=True, verbose_name='空调数量'),
        ),
        migrations.AddField(
            model_name='houseinfo',
            name='bed',
            field=models.CharField(max_length=4, null=True, verbose_name='床数目'),
        ),
        migrations.AddField(
            model_name='houseinfo',
            name='blower',
            field=models.CharField(max_length=4, null=True, verbose_name='风扇数量'),
        ),
        migrations.AddField(
            model_name='houseinfo',
            name='chair',
            field=models.CharField(max_length=4, null=True, verbose_name='椅子数目'),
        ),
        migrations.AddField(
            model_name='houseinfo',
            name='else_support',
            field=models.CharField(max_length=256, null=True, verbose_name='其他配套设施补充'),
        ),
        migrations.AddField(
            model_name='houseinfo',
            name='power',
            field=models.CharField(max_length=10, null=True, verbose_name='电量'),
        ),
        migrations.AddField(
            model_name='houseinfo',
            name='table',
            field=models.CharField(max_length=4, null=True, verbose_name='桌子数目'),
        ),
        migrations.AddField(
            model_name='houseinfo',
            name='water',
            field=models.CharField(max_length=10, null=True, verbose_name='水量'),
        ),
    ]
