# Generated by Django 2.1.4 on 2019-11-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0023_auto_20191128_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydropower',
            name='last_time',
            field=models.DateField(auto_now=True, verbose_name='最近更新时间'),
        ),
    ]
