# Generated by Django 2.1.4 on 2019-11-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0026_auto_20191128_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='last_time',
            field=models.DateField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AlterField(
            model_name='hydropower',
            name='last_time',
            field=models.DateField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
    ]
