# Generated by Django 2.1.4 on 2019-11-29 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog2', '0027_auto_20191128_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', '退房申请'), ('1', '房屋配套申请'), ('2', '其他申请')], default='0', max_length=50, verbose_name='申请类型')),
                ('content', models.CharField(default='', max_length=300, verbose_name='申请内容')),
                ('remark', models.CharField(default='', max_length=300, verbose_name='备注')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('last_time', models.DateField(auto_now=True, verbose_name='最新编辑时间')),
                ('username', models.ForeignKey(default=None, max_length=60, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
        ),
        migrations.DeleteModel(
            name='Check_out_application',
        ),
        migrations.DeleteModel(
            name='Housing_Supporting_Facilities_application',
        ),
    ]
