# Generated by Django 2.1.4 on 2019-12-03 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog2', '0028_auto_20191129_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_list',
            name='username',
        ),
        migrations.AddField(
            model_name='application_list',
            name='status',
            field=models.CharField(choices=[('0', '待审核'), ('1', '审核通过'), ('2', '审核不通过')], default='0', max_length=5, verbose_name='申请状态'),
        ),
        migrations.AddField(
            model_name='application_list',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AlterField(
            model_name='application_list',
            name='remark',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='备注'),
        ),
    ]
