# Generated by Django 2.1.4 on 2019-12-03 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog2', '0029_auto_20191203_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_list',
            name='user',
        ),
        migrations.AddField(
            model_name='application_list',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
