# Generated by Django 2.1.4 on 2019-12-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0030_auto_20191203_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='openid',
            field=models.CharField(blank=True, max_length=64, verbose_name='openid'),
        ),
    ]
