# Generated by Django 2.1.4 on 2019-12-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0031_userprofile_openid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_list',
            name='remark',
            field=models.CharField(default='', max_length=300, verbose_name='备注'),
        ),
    ]
