# Generated by Django 2.1.4 on 2019-12-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0034_userprofile_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uuid',
            field=models.CharField(blank=True, max_length=64, verbose_name='uuid'),
        ),
    ]
