# Generated by Django 2.1.4 on 2020-01-14 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0035_userprofile_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaction', models.CharField(blank=True, max_length=60, verbose_name='Loaction')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog2.organization', verbose_name='org'),
        ),
    ]
