# Generated by Django 2.1.4 on 2020-01-16 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0036_auto_20200114_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'organization'},
        ),
    ]
